title: "Minoxidilbg"
email: "minoxidilbg @ gmail.com"
description: "Миноксидил 2% и 5% за мъже и жени. Всичко за лечение на косопад, алопеция и стимулиране на растежа на нова коса."
author: "MinoxidilBG"
lang: "bg"
timezone: Europe/Sofia
baseurl: "/minoxidilbg" # остави празно, защото сайтът е на root
url: "https://lolopetrov.github.io"
permalink: /:year/:month/:day/:title:output_ext

keywords:
  - миноксидил
  - миноксидил 5%
  - миноксидил за мъже
  - миноксидил 2%
  - миноксидил за жени
  - лечение на косопад
  - андрогенна алопеция
  - растеж на косата
  - косопад при мъже
  - косопад при жени
  - локално приложение
  - резултати от миноксидил
  - миноксидилbg

seo:
  type: website
  name: "MinoxidilBG"
  description: "Миноксидил срещу косопад за мъже и жени"
  twitter:
    username: "minoxidilbg"
  facebook:
    app_id: ""

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
